# Generated by Django 5.2.17 on 2026-09-10 04:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('MANUAL', 'Manual'), ('VERIFY', 'Restore verification')], default='SCHEDULED', max_length=10)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='RUNNING', max_length=8)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('archive_name', models.CharField(blank=True, max_length=200)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('database_ok', models.BooleanField(default=False)),
                ('media_ok', models.BooleanField(default=False)),
                ('encrypted', models.BooleanField(default=True)),
                ('archives_retained', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('host', models.CharField(blank=True, max_length=100)),
                ('build', models.CharField(blank=True, max_length=60)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reporting_backup_run',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status', 'started_at'], name='reporting_b_status_e04887_idx'), models.Index(fields=['kind', 'started_at'], name='reporting_b_kind_7f1884_idx')],
            },
        ),
    ]
