# Generated by Django 5.2.17 on 2026-09-04 05:41

import apps.core.fields
import apps.core.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('max_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('released', models.BooleanField(default=False, help_text='Parent-visible once released.')),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='people.group')),
            ],
            options={
                'db_table': 'grades_assessment',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mark', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('narrative', apps.core.fields.EncryptedTextField(blank=True, default='')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='grades.assessment')),
                ('graded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to='people.student')),
            ],
            options={
                'db_table': 'grades_assessment_result',
            },
        ),
        migrations.CreateModel(
            name='AssessmentScheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('MARKS', 'Marks / percentage'), ('RUBRIC', 'Rubric levels'), ('NARRATIVE', 'Narrative only'), ('MIXED', 'Rubric + narrative + marks')], default='MIXED', max_length=10)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_schemes', to='people.group')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_schemes', to='scheduling.term')),
            ],
            options={
                'db_table': 'grades_assessment_scheme',
                'ordering': ['group', 'name'],
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='grades.assessmentscheme'),
        ),
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINALIZED', 'Finalized'), ('RELEASED', 'Released to guardians')], default='DRAFT', max_length=10)),
                ('summary_narrative', apps.core.fields.EncryptedTextField(blank=True, default='')),
                ('document', models.FileField(blank=True, storage=apps.core.storage.document_storage, upload_to='report-cards/%Y/')),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='people.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_cards', to='scheduling.term')),
            ],
            options={
                'db_table': 'grades_report_card',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportCardEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=150)),
                ('mark', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comment', apps.core.fields.EncryptedTextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=1)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='people.group')),
                ('report_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='grades.reportcard')),
            ],
            options={
                'db_table': 'grades_report_card_entry',
                'ordering': ['report_card', 'order'],
            },
        ),
        migrations.CreateModel(
            name='RubricCriterion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=150)),
                ('descriptor', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('max_level', models.PositiveSmallIntegerField(default=4)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='grades.assessmentscheme')),
            ],
            options={
                'db_table': 'grades_rubric_criterion',
                'ordering': ['scheme', 'order'],
            },
        ),
        migrations.CreateModel(
            name='RubricScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.PositiveSmallIntegerField()),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='grades.rubriccriterion')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_scores', to='grades.assessmentresult')),
            ],
            options={
                'db_table': 'grades_rubric_score',
            },
        ),
        migrations.AddConstraint(
            model_name='assessmentresult',
            constraint=models.UniqueConstraint(fields=('assessment', 'student'), name='uniq_result_per_student'),
        ),
        migrations.AddConstraint(
            model_name='reportcard',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('student', 'term'), name='uniq_report_card_per_term'),
        ),
        migrations.AddConstraint(
            model_name='rubricscore',
            constraint=models.UniqueConstraint(fields=('result', 'criterion'), name='uniq_score_per_criterion'),
        ),
    ]
