# Generated by Django 5.2.17 on 2026-09-12 21:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingScheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uses_gpa', models.BooleanField(default=False, help_text='If on, a cumulative GPA is computed and printed on report cards.')),
                ('gpa_scale', models.DecimalField(blank=True, decimal_places=2, help_text='e.g. 4.00 or 5.00 - documentation only, bands carry the real points.', max_digits=3, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'grades_grading_scheme',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='reportcard',
            name='cumulative_gpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Computed at generation time from entries whose mark maps to a GPA-bearing band. Unweighted (Campus doesn't model credit-hours).", max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='grading_scheme',
            field=models.ForeignKey(blank=True, help_text="The scheme active when this card was generated - a historical snapshot, not a live pointer, so a later policy change doesn't rewrite old cards.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='grades.gradingscheme'),
        ),
        migrations.CreateModel(
            name='GradeBand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text='What prints on the report card: A, Level 4, 7, Distinction…', max_length=30)),
                ('min_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gpa_points', models.DecimalField(blank=True, decimal_places=2, help_text='Only meaningful when the scheme uses_gpa.', max_digits=3, null=True)),
                ('description', models.CharField(blank=True, max_length=150)),
                ('order', models.PositiveIntegerField(default=1, help_text='Display order, highest band first.')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='grades.gradingscheme')),
            ],
            options={
                'db_table': 'grades_grade_band',
                'ordering': ['scheme', 'order'],
                'constraints': [models.UniqueConstraint(fields=('scheme', 'label'), name='uniq_band_label_per_scheme')],
            },
        ),
    ]
