# Generated by Django 5.2.17 on 2026-09-04 05:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('EXPECTED', 'Expected'), ('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('EXCUSED', 'Excused absence'), ('LEFT_EARLY', 'Left early')], default='EXPECTED', max_length=12)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('dropped_off_by_name', models.CharField(blank=True, max_length=150)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('collected_by_name', models.CharField(blank=True, max_length=150)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('checked_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('collected_by_guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='people.guardianlink')),
                ('collected_by_pickup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='people.authorizedpickup')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='people.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='people.student')),
            ],
            options={
                'db_table': 'attendance_record',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['group', 'date'], name='attendance__group_i_583405_idx'), models.Index(fields=['date', 'status'], name='attendance__date_6a3408_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'group', 'date'), name='uniq_attendance_per_day')],
            },
        ),
    ]
