# Generated by Django 5.2.17 on 2026-09-04 05:41

import apps.core.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('ANNOUNCEMENT', 'Announcement'), ('INCIDENT', 'Incident report'), ('THREAD', 'Message thread'), ('REPORT_CARD', 'Report card released')], max_length=12)),
                ('subject', models.CharField(max_length=255)),
                ('to', models.JSONField(default=list)),
                ('object_type', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'communication_outbound_email',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('audience', models.CharField(choices=[('ALL_STAFF', 'All staff'), ('ALL_PARENTS', 'All parents'), ('GROUP', "One group's parents"), ('WHOLE_SITE', 'Everyone')], max_length=12)),
                ('pinned', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='people.group')),
            ],
            options={
                'db_table': 'communication_announcement',
                'ordering': ['-pinned', '-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('occurred_at', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=150)),
                ('category', models.CharField(choices=[('INJURY', 'Injury'), ('BEHAVIOUR', 'Behaviour'), ('ILLNESS', 'Illness'), ('ALLERGY', 'Allergic reaction'), ('SAFEGUARDING', 'Safeguarding'), ('OTHER', 'Other')], default='OTHER', max_length=13)),
                ('severity', models.PositiveSmallIntegerField(default=1, help_text='1 minor – 5 serious')),
                ('description', apps.core.fields.EncryptedTextField()),
                ('action_taken', apps.core.fields.EncryptedTextField(blank=True, default='')),
                ('first_aid_given', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent to guardians'), ('ACKNOWLEDGED', 'Acknowledged')], default='DRAFT', max_length=12)),
                ('guardians_notified_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to='people.student')),
            ],
            options={
                'db_table': 'communication_incident_report',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentAcknowledgement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signature_name', models.CharField(max_length=150)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('acknowledged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='people.guardian')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='communication.incidentreport')),
            ],
            options={
                'db_table': 'communication_incident_ack',
            },
        ),
        migrations.CreateModel(
            name='MessageThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=200)),
                ('closed', models.BooleanField(default=False)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='message_threads', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_threads', to='people.student')),
            ],
            options={
                'db_table': 'communication_message_thread',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', apps.core.fields.EncryptedTextField()),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communication.messagethread')),
            ],
            options={
                'db_table': 'communication_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['student', 'occurred_at'], name='communicati_student_491991_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['status'], name='communicati_status_10b10b_idx'),
        ),
        migrations.AddConstraint(
            model_name='incidentacknowledgement',
            constraint=models.UniqueConstraint(fields=('incident', 'guardian'), name='uniq_incident_ack_per_guardian'),
        ),
    ]
