# Generated by Django 5.2.17 on 2026-09-10 23:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('INCIDENT', 'Incident notification'), ('REPORT_CARD', 'Report card released'), ('ABSENCE', 'Absence notification'), ('ANNOUNCEMENT', 'Announcement email'), ('GENERAL', 'General / ad-hoc')], default='GENERAL', max_length=16)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'communication_message_template',
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='outboundemail',
            name='kind',
            field=models.CharField(choices=[('ANNOUNCEMENT', 'Announcement'), ('INCIDENT', 'Incident report'), ('THREAD', 'Message thread'), ('REPORT_CARD', 'Report card released'), ('ABSENCE', 'Absence notification')], max_length=12),
        ),
    ]
