# Generated by Django 5.2.17 on 2026-09-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_seed_system_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboundemail',
            name='kind',
            field=models.CharField(choices=[('ANNOUNCEMENT', 'Announcement'), ('INCIDENT', 'Incident report'), ('THREAD', 'Message thread'), ('REPORT_CARD', 'Report card released'), ('ABSENCE', 'Absence notification'), ('CONSENT', 'Consent request')], max_length=12),
        ),
    ]
