# Generated by Django 5.2.17 on 2026-09-04 04:22

import apps.core.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('kind', models.CharField(choices=[('ANAPHYLAXIS', 'Anaphylaxis'), ('ASTHMA', 'Asthma'), ('SEIZURE', 'Seizure'), ('DIABETES', 'Diabetes'), ('OTHER', 'Other')], max_length=12)),
                ('plan', apps.core.fields.EncryptedTextField()),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('review_by', models.DateField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='people.document')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='people.student')),
            ],
            options={
                'db_table': 'health_action_plan',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allergen', apps.core.fields.EncryptedCharField(max_length=512)),
                ('reaction', apps.core.fields.EncryptedTextField(blank=True, default='')),
                ('severity', models.CharField(choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe'), ('ANAPHYLAXIS', 'Anaphylaxis')], default='MODERATE', max_length=12)),
                ('epipen_required', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='people.student')),
            ],
            options={
                'verbose_name_plural': 'allergies',
                'db_table': 'health_allergy',
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', apps.core.fields.EncryptedCharField(max_length=512)),
                ('details', apps.core.fields.EncryptedTextField(blank=True, default='')),
                ('diagnosed_on', models.DateField(blank=True, null=True)),
                ('ongoing', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='people.student')),
            ],
            options={
                'db_table': 'health_condition',
            },
        ),
        migrations.CreateModel(
            name='HealthAccessGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health_access_grant',
            },
        ),
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blood_type', apps.core.fields.EncryptedCharField(blank=True, default='', max_length=512)),
                ('notes', apps.core.fields.EncryptedTextField(blank=True, default='')),
                ('last_reviewed_at', models.DateField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to='people.student')),
            ],
            options={
                'db_table': 'health_profile',
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', apps.core.fields.EncryptedCharField(max_length=512)),
                ('dose', apps.core.fields.EncryptedCharField(blank=True, default='', max_length=512)),
                ('schedule', apps.core.fields.EncryptedCharField(blank=True, default='', max_length=512)),
                ('route', models.CharField(choices=[('ORAL', 'Oral'), ('TOPICAL', 'Topical'), ('INHALED', 'Inhaled'), ('INJECTION', 'Injection'), ('OTHER', 'Other')], default='ORAL', max_length=10)),
                ('prn', models.BooleanField(default=False, help_text='Given as needed rather than scheduled.')),
                ('prescriber', apps.core.fields.EncryptedCharField(blank=True, default='', max_length=512)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='people.student')),
            ],
            options={
                'db_table': 'health_medication',
            },
        ),
    ]
