# Generated by Django 5.2.17 on 2026-09-04 04:22

import apps.core.fields
import apps.core.storage
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('child_first_name', models.CharField(max_length=100)),
                ('child_last_name', models.CharField(max_length=100)),
                ('child_date_of_birth', models.DateField()),
                ('desired_start', models.DateField(blank=True, null=True)),
                ('applicant_name', models.CharField(max_length=200)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('applicant_phone', apps.core.fields.EncryptedCharField(blank=True, default='', max_length=512)),
                ('notes', apps.core.fields.EncryptedTextField(blank=True, default='')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('OFFER_MADE', 'Offer made'), ('WAITLISTED', 'Waitlisted'), ('ENROLLED', 'Enrolled'), ('DECLINED', 'Declined'), ('WITHDRAWN', 'Withdrawn')], default='SUBMITTED', max_length=14)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('desired_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='people.group')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='people.student')),
            ],
            options={
                'db_table': 'registration_application',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(storage=apps.core.storage.document_storage, upload_to='applications/%Y/%m/')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='registration.application')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'registration_application_document',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='registration.application')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='people.group')),
                ('made_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'registration_offer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.IntegerField(default=100, help_text='Lower sorts first.')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entry', to='registration.application')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist', to='people.group')),
            ],
            options={
                'verbose_name_plural': 'waitlist entries',
                'db_table': 'registration_waitlist_entry',
                'ordering': ['priority', 'added_at'],
            },
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('PHOTO', 'Photography'), ('MEDIA', 'Media / publicity'), ('FIELD_TRIP', 'Off-site excursions'), ('DATA_SHARING', 'Information sharing with third parties'), ('MEDICAL_TREATMENT', 'Emergency medical treatment'), ('TECHNOLOGY', 'Technology / internet use'), ('SUNSCREEN', 'Sunscreen / topical application')], max_length=20)),
                ('version', models.CharField(default='1', max_length=20)),
                ('granted', models.BooleanField()),
                ('granted_by_name', models.CharField(blank=True, max_length=200)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', apps.core.fields.EncryptedTextField(blank=True, default='')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consents_given', to='people.guardian')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='people.student')),
            ],
            options={
                'db_table': 'registration_consent',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['student', 'kind', 'recorded_at'], name='registratio_student_63594e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ENDED', 'Ended')], default='ACTIVE', max_length=8)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolments', to='people.group')),
                ('source_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolments', to='registration.application')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='people.student')),
            ],
            options={
                'db_table': 'registration_enrolment',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['group', 'status'], name='registratio_group_i_d1e69f_idx'), models.Index(fields=['student', 'status'], name='registratio_student_a09bc6_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('student', 'group'), name='uniq_active_enrolment_per_group')],
            },
        ),
    ]
