# Generated by Django 5.2.17 on 2026-09-10 23:09

import apps.core.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('motto', models.CharField(blank=True, max_length=200)),
                ('address_line1', models.CharField(blank=True, max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.CharField(blank=True, max_length=200)),
                ('principal_name', models.CharField(blank=True, max_length=150)),
                ('principal_title', models.CharField(blank=True, default='Principal', max_length=80)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.core.models._school_logo_path)),
                ('report_card_footer', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'school profile',
                'db_table': 'core_school_profile',
            },
        ),
    ]
