# Generated by Django 5.2.17 on 2026-09-11 00:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('currency', models.CharField(default='CAD', max_length=3)),
                ('locale', models.CharField(blank=True, max_length=10)),
                ('collects_fees', models.BooleanField(default=True)),
                ('deployment_mode', models.CharField(choices=[('SINGLE', 'Single institution'), ('SCHOOL', 'School (spoke of a headquarters)'), ('HEADQUARTERS', 'Headquarters')], default='SINGLE', max_length=12)),
            ],
            options={
                'verbose_name': 'site configuration',
                'db_table': 'core_site_configuration',
            },
        ),
    ]
