# Generated by Django 5.2.17 on 2026-09-11 04:09

import apps.core.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_siteconfiguration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='principal_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='signature',
            field=models.ImageField(blank=True, null=True, storage=apps.core.storage.document_storage, upload_to='school/signatures/%Y/'),
        ),
    ]
