# Generated by Django 5.2.17 on 2026-09-11 00:22

import apps.core.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0003_student_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IEP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('school_year', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('UNDER_REVIEW', 'Under review'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=12)),
                ('primary_concern', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('strengths', apps.core.fields.EncryptedTextField(blank=True, default='')),
                ('needs', apps.core.fields.EncryptedTextField(blank=True, default='')),
                ('summary', apps.core.fields.EncryptedTextField(blank=True, default='')),
                ('case_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ieps', to='people.student')),
            ],
            options={
                'db_table': 'iep_iep',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IEPAccommodation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('PRESENTATION', 'Presentation'), ('RESPONSE', 'Response'), ('SETTING', 'Setting / environment'), ('TIMING', 'Timing / scheduling'), ('ASSISTIVE_TECH', 'Assistive technology'), ('OTHER', 'Other')], default='OTHER', max_length=16)),
                ('description', apps.core.fields.EncryptedTextField()),
                ('applies_to', models.CharField(blank=True, default='All classes', max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('iep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='iep.iep')),
            ],
            options={
                'db_table': 'iep_accommodation',
                'ordering': ['category', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='IEPGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.CharField(choices=[('READING', 'Reading'), ('WRITING', 'Writing'), ('MATH', 'Mathematics'), ('COMMUNICATION', 'Communication / language'), ('SOCIAL_EMOTIONAL', 'Social / emotional'), ('BEHAVIOUR', 'Behaviour / self-regulation'), ('MOTOR', 'Fine / gross motor'), ('ORGANISATION', 'Organisation / executive function'), ('LIFE_SKILLS', 'Life / independence skills'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('description', apps.core.fields.EncryptedTextField()),
                ('baseline', apps.core.fields.EncryptedTextField(blank=True, default='')),
                ('target', apps.core.fields.EncryptedTextField(blank=True, default='')),
                ('progress', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('EMERGING', 'Emerging'), ('PROGRESSING', 'Progressing'), ('MET', 'Met'), ('DISCONTINUED', 'Discontinued')], default='NOT_STARTED', max_length=12)),
                ('progress_notes', apps.core.fields.EncryptedTextField(blank=True, default='')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('iep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='iep.iep')),
            ],
            options={
                'db_table': 'iep_goal',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='IEPReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_date', models.DateField()),
                ('attendees', models.CharField(blank=True, max_length=255)),
                ('outcome', models.CharField(choices=[('CONTINUE', 'Continue as written'), ('REVISE', 'Revise the plan'), ('EXIT', 'Exit / discontinue'), ('REFER', 'Refer for further assessment')], default='CONTINUE', max_length=10)),
                ('notes', apps.core.fields.EncryptedTextField(blank=True, default='')),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('iep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='iep.iep')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'iep_review',
                'ordering': ['-review_date'],
            },
        ),
        migrations.CreateModel(
            name='IEPService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.CharField(max_length=150)),
                ('provider', models.CharField(blank=True, max_length=150)),
                ('frequency', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', apps.core.fields.EncryptedTextField(blank=True, default='')),
                ('iep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='iep.iep')),
            ],
            options={
                'db_table': 'iep_service',
                'ordering': ['service', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='iep',
            index=models.Index(fields=['student', 'status'], name='iep_iep_student_2e724a_idx'),
        ),
    ]
