# Generated by Django 5.2.17 on 2026-09-04 03:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_label', models.CharField(blank=True, max_length=150)),
                ('actor_role', models.CharField(blank=True, max_length=16)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGIN_FAILED', 'Login failed'), ('LOGOUT', 'Logout'), ('LOCKOUT', 'Lockout'), ('MFA_ENROLLED', 'MFA enrolled'), ('MFA_VERIFIED', 'MFA verified'), ('EXPORT', 'Data export'), ('ERASE', 'Erasure'), ('PERMISSION_DENIED', 'Permission denied')], db_index=True, max_length=20)),
                ('object_type', models.CharField(blank=True, db_index=True, max_length=100)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_entry',
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['object_type', 'object_id', 'at'], name='audit_entry_object__7c2540_idx'), models.Index(fields=['actor', 'at'], name='audit_entry_actor_i_1f06b3_idx'), models.Index(fields=['action', 'at'], name='audit_entry_action_9f4e42_idx')],
            },
        ),
    ]
