# Generated by Django 5.2.17 on 2026-09-11 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
