# Generated by Django 5.2.17 on 2026-09-12 20:17, hand-edited to backfill
# existing rows before the unique constraint applies (see the comment on
# _backfill_invoice_numbers - a plain AddField(unique=True) fails outright
# against any database that already has more than one Invoice row, since
# they'd all share the column's blank default and collide on uniqueness).

from django.db import migrations, models


def _backfill_invoice_numbers(apps, schema_editor):
    Invoice = apps.get_model("billing", "Invoice")
    for n, invoice in enumerate(Invoice.objects.order_by("created_at"), start=1):
        invoice.invoice_number = f"INV-{n:06d}"
        invoice.save(update_fields=["invoice_number"])


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_backfill_invoice_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, default='', editable=False, help_text='Human-readable reference (INV-000123), assigned on creation.', max_length=20),
            preserve_default=False,
        ),
        migrations.RunPython(_backfill_invoice_numbers, _noop_reverse),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, editable=False, help_text='Human-readable reference (INV-000123), assigned on creation.', max_length=20, unique=True),
        ),
    ]
