# Generated by Django 5.2.17 on 2026-09-16 16:56

import apps.core.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_invoice_invoice_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gateway',
            field=models.CharField(blank=True, choices=[('MANUAL', 'Manual only'), ('PAYSTACK', 'Paystack'), ('FLUTTERWAVE', 'Flutterwave'), ('STRIPE', 'Stripe'), ('KANOO', 'Kanoo')], default='', max_length=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('GATEWAY', 'Online gateway')], default='MANUAL', max_length=7),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('E_TRANSFER', 'e-Transfer'), ('CARD_TERMINAL', 'Card — terminal'), ('OTHER', 'Other')], default='', max_length=13),
        ),
        migrations.CreateModel(
            name='GatewayConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gateway', models.CharField(choices=[('MANUAL', 'Manual only'), ('PAYSTACK', 'Paystack'), ('FLUTTERWAVE', 'Flutterwave'), ('STRIPE', 'Stripe'), ('KANOO', 'Kanoo')], default='MANUAL', max_length=12)),
                ('mode', models.CharField(choices=[('TEST', 'Test'), ('LIVE', 'Live')], default='TEST', max_length=4)),
                ('public_key', models.CharField(blank=True, default='', max_length=255)),
                ('secret_key', apps.core.fields.EncryptedCharField(blank=True, default='', max_length=255)),
                ('subaccount_id', models.CharField(blank=True, default='', max_length=100)),
                ('configured_at', models.DateTimeField(blank=True, null=True)),
                ('configured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'gateway configuration',
                'db_table': 'billing_gateway_config',
            },
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gateway', models.CharField(choices=[('MANUAL', 'Manual only'), ('PAYSTACK', 'Paystack'), ('FLUTTERWAVE', 'Flutterwave'), ('STRIPE', 'Stripe'), ('KANOO', 'Kanoo')], max_length=12)),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('amount_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('INITIALIZED', 'Initialized'), ('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('ABANDONED', 'Abandoned'), ('MISMATCH', 'Mismatch')], default='INITIALIZED', max_length=11)),
                ('checkout_url', models.CharField(blank=True, default='', max_length=500)),
                ('channel', models.CharField(blank=True, default='', max_length=30)),
                ('raw_response', apps.core.fields.EncryptedTextField(blank=True, default='')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('initialized_by', models.ForeignKey(blank=True, help_text='Who triggered checkout - the parent from the portal, or staff generating a payment link.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='billing.invoice')),
            ],
            options={
                'db_table': 'billing_payment_attempt',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['invoice', 'status'], name='billing_pay_invoice_9f00c4_idx')],
            },
        ),
    ]
