# Generated by Django 5.2.17 on 2026-09-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_gateway_config_and_payment_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentattempt',
            name='gateway_session_id',
            field=models.CharField(blank=True, default='', help_text="The gateway's OWN id for this checkout, when it has one distinct from `reference` (e.g. Stripe's Checkout Session id - Stripe has no verify-by-your-own-reference endpoint, only by its own id). Blank for a gateway that verifies by `reference` directly (Paystack, Flutterwave).", max_length=255),
        ),
    ]
