# Generated by Django 5.2.17 on 2026-09-16 20:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_paymentattempt_gateway_session_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAttemptInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_cents', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'billing_payment_attempt_invoice',
            },
        ),
        migrations.RemoveIndex(
            model_name='paymentattempt',
            name='billing_pay_invoice_9f00c4_idx',
        ),
        migrations.RemoveField(
            model_name='paymentattempt',
            name='invoice',
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['gateway', 'status'], name='billing_pay_gateway_09c039_idx'),
        ),
        migrations.AddField(
            model_name='paymentattemptinvoice',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='billing.paymentattempt'),
        ),
        migrations.AddField(
            model_name='paymentattemptinvoice',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempt_allocations', to='billing.invoice'),
        ),
        migrations.AddConstraint(
            model_name='paymentattemptinvoice',
            constraint=models.UniqueConstraint(fields=('attempt', 'invoice'), name='one_allocation_per_invoice_per_attempt'),
        ),
    ]
