# Generated by Django 5.2.17 on 2026-09-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SICK_LEAVE', 'Sick leave'), ('ON_LEAVE', 'On leave'), ('SEDENTARY_DUTY', 'Sedentary duty'), ('TRANSFERRED', 'Transferred'), ('SUSPENDED', 'Suspended'), ('TERMINATED', 'Terminated')], default='ACTIVE', help_text='Meaningful for staff roles; portal accounts stay ACTIVE.', max_length=16),
        ),
    ]
