# Generated by Django 5.2.17 on 2026-09-11 04:32

import apps.core.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffChatCursor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_read_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staffchat_cursor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staffchat_cursor',
            },
        ),
        migrations.CreateModel(
            name='StaffMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audience', models.CharField(choices=[('DIRECT', 'Direct message'), ('TEACHERS', 'All teachers'), ('TUTORS', 'All tutors'), ('ALL_STAFF', 'All staff')], default='DIRECT', max_length=10)),
                ('body', apps.core.fields.EncryptedTextField()),
                ('urgent', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(blank=True, help_text='Null for a role broadcast.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staffchat_message',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'created_at'], name='staffchat_m_recipie_767ff9_idx'), models.Index(fields=['audience', 'created_at'], name='staffchat_m_audienc_d7be58_idx')],
            },
        ),
    ]
