# Generated by Django 5.2.17 on 2026-09-04 04:22

import apps.core.fields
import apps.core.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('ROOM', 'Daycare room'), ('CLASS', 'Class'), ('SECTION', 'Course section')], default='CLASS', max_length=10)),
                ('stage_label', models.CharField(blank=True, help_text="Free label, e.g. 'Toddler', 'Grade 4', 'SNC2D'.", max_length=60)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'people_group',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', apps.core.fields.EncryptedCharField(blank=True, default='', max_length=512)),
                ('address', apps.core.fields.EncryptedTextField(blank=True, default='')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'people_guardian',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('preferred_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField()),
                ('pronouns', models.CharField(blank=True, max_length=40)),
                ('student_number', models.CharField(max_length=20, unique=True)),
                ('government_id', apps.core.fields.EncryptedCharField(blank=True, default='', max_length=512)),
                ('custody_notes', apps.core.fields.EncryptedTextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PROSPECTIVE', 'Prospective'), ('ENROLLED', 'Enrolled'), ('WITHDRAWN', 'Withdrawn'), ('GRADUATED', 'Graduated')], default='PROSPECTIVE', max_length=12)),
                ('left_on', models.DateField(blank=True, help_text='Withdrawn / graduated date; starts the retention clock.', null=True)),
                ('legal_hold', models.BooleanField(default=False, help_text='Blocks retention purge and the erase-this-person action.')),
                ('anonymized_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('primary_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_students', to='people.group')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'people_student',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('category', models.CharField(choices=[('DEVELOPMENTAL', 'Developmental'), ('BEHAVIOURAL', 'Behavioural'), ('ACADEMIC', 'Academic'), ('INCIDENT', 'Incident'), ('MEDICAL', 'Medical'), ('GENERAL', 'General')], default='GENERAL', max_length=14)),
                ('occurred_at', models.DateTimeField()),
                ('body', apps.core.fields.EncryptedTextField()),
                ('visible_to_guardians', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='people.student')),
            ],
            options={
                'db_table': 'people_observation',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='GuardianLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.CharField(choices=[('MOTHER', 'Mother'), ('FATHER', 'Father'), ('PARENT', 'Parent'), ('GRANDPARENT', 'Grandparent'), ('LEGAL_GUARDIAN', 'Legal guardian'), ('FOSTER', 'Foster carer'), ('OTHER', 'Other')], max_length=16)),
                ('is_primary_contact', models.BooleanField(default=False)),
                ('has_custody', models.BooleanField(default=True)),
                ('can_pickup', models.BooleanField(default=True)),
                ('receives_communications', models.BooleanField(default=True)),
                ('lives_with', models.BooleanField(default=True)),
                ('custody_notes', apps.core.fields.EncryptedTextField(blank=True, default='')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='people.guardian')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_links', to='people.student')),
            ],
            options={
                'db_table': 'people_guardian_link',
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('relationship', models.CharField(max_length=60)),
                ('phone', apps.core.fields.EncryptedCharField(blank=True, default='', max_length=512)),
                ('alt_phone', apps.core.fields.EncryptedCharField(blank=True, default='', max_length=512)),
                ('priority', models.PositiveSmallIntegerField(default=1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='people.student')),
            ],
            options={
                'db_table': 'people_emergency_contact',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('kind', models.CharField(choices=[('BIRTH_CERTIFICATE', 'Birth certificate'), ('IMMUNIZATION', 'Immunization record'), ('CUSTODY_ORDER', 'Custody / court order'), ('IEP', 'IEP / support plan'), ('PHOTO', 'Photo'), ('CONSENT_FORM', 'Signed consent form'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(storage=apps.core.storage.document_storage, upload_to='documents/%Y/%m/')),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('byte_size', models.PositiveIntegerField(default=0)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='people.student')),
            ],
            options={
                'db_table': 'people_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthorizedPickup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('relationship', models.CharField(max_length=60)),
                ('phone', apps.core.fields.EncryptedCharField(blank=True, default='', max_length=512)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_pickups', to='people.student')),
            ],
            options={
                'db_table': 'people_authorized_pickup',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroupStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('LEAD', 'Lead'), ('ASSISTANT', 'Assistant')], default='LEAD', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='people.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'people_group_staff',
                'constraints': [models.UniqueConstraint(fields=('group', 'user'), name='uniq_group_staff')],
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['status', 'last_name'], name='people_stud_status_e93e2d_idx'),
        ),
        migrations.AddConstraint(
            model_name='guardianlink',
            constraint=models.UniqueConstraint(fields=('student', 'guardian'), name='uniq_student_guardian'),
        ),
    ]
