# Generated by Django 5.2.17 on 2026-09-11 00:07

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_contactchangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=apps.core.storage.document_storage, upload_to='student-photos/%Y/'),
        ),
    ]
