# Generated by Django 5.2.17 on 2026-09-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='government_id_type',
            field=models.CharField(blank=True, choices=[('NATIONAL_ID', 'National ID'), ('PASSPORT', 'Passport'), ('BIRTH_CERTIFICATE', 'Birth certificate number'), ('SOCIAL_INSURANCE', 'Social insurance / security number'), ('VOTER_ID', 'Voter ID'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
