# Generated by Django 5.2.17 on 2026-09-04 05:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'scheduling_academic_year',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('kind', models.CharField(choices=[('CLASSROOM', 'Classroom'), ('GYM', 'Gym / activity hall'), ('OUTDOOR', 'Outdoor space'), ('RESOURCE', 'Shared resource')], default='CLASSROOM', max_length=10)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'scheduling_room',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Closure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(max_length=200)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closures', to='people.group')),
            ],
            options={
                'db_table': 'scheduling_closure',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('kind', models.CharField(choices=[('SEMESTER', 'Semester'), ('TRIMESTER', 'Trimester'), ('QUARTER', 'Quarter'), ('ROLLING', 'Rolling / continuous'), ('YEAR_ROUND', 'Year-round')], default='SEMESTER', max_length=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='scheduling.academicyear')),
            ],
            options={
                'db_table': 'scheduling_term',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='SessionTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('title', models.CharField(blank=True, max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_templates', to='people.group')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_templates', to='scheduling.room')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_templates', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_templates', to='scheduling.term')),
            ],
            options={
                'db_table': 'scheduling_session_template',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='SessionOccurrence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('title', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=10)),
                ('cancelled_reason', models.CharField(blank=True, max_length=200)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_occurrences', to='people.group')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_occurrences', to='scheduling.room')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_occurrences', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='scheduling.sessiontemplate')),
            ],
            options={
                'db_table': 'scheduling_session_occurrence',
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['group', 'date'], name='scheduling__group_i_aff1a0_idx'), models.Index(fields=['date', 'status'], name='scheduling__date_960a23_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('template__isnull', False)), fields=('template', 'date'), name='uniq_occurrence_per_template_date')],
            },
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('academic_year', 'name'), name='uniq_term_per_year'),
        ),
    ]
