# Generated by Django 5.2.17 on 2026-09-11 15:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_student_photo'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarlyDismissal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('dismissal_time', models.TimeField(help_text='The new end-of-day time.')),
                ('reason', models.CharField(max_length=200)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(blank=True, help_text='Blank = site-wide.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='early_dismissals', to='people.group')),
            ],
            options={
                'db_table': 'scheduling_early_dismissal',
                'ordering': ['date'],
            },
        ),
    ]
